---
title: "Analytics Report for Ekstraklasa"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
    theme:
      version: 4
      bg: "#101010"
      fg: "#FDF7F7" 
      primary: "#ED79F9"
      navbar-bg: "#3ADAC6"
      base_font: 
        google: Prompt
      heading_font:
        google: Sen
      code_font:
        google: 
          # arguments to sass::font_google() 
          family: JetBrains Mono
          local: false
    source_code: https://github.com/LukaszChrostowski/Football_Results_Predictions
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(plotly)
library(ggplot2)
library(dplyr)
library(lubridate)
library(lattice)
library(shiny)
library(xgboost)

load("output_data/processed_data.Rdata")
load("data/contingency_table.Rdata")
df <- proccessed_data
```


```{r}
# FUNCTIONS

# Descriptive plots for the choosen season
ConvFun <- function(data) {
  
  data[data == "H"] <- 1
  data[data == "D"] <- 2
  data[data == "A"] <- 3
  
  for (col in colnames(data)) {
    
    data[, col] <- as.numeric(data[, col])
    
  }
  data <- as.matrix(data)
  data
}

levelplotFun <- function(data){
  
  plt <- levelplot(t(data[c(nrow(data):1), ]), scales=list(x=list(rot=45)),
                   col.regions = colorRampPalette(c("green", "yellow", "red"))(100),
                   colorkey=FALSE,
                   xlab = "Gość", ylab = "Gospodarz")
  plt
}
```

{.sidebar}
======================================================================

```{r}
# selectInput("x_variable", label = "First variable:",
#             choices = c("Posiadanie piłki Gospodarz", "Sytuacje bramkowe Gospodarz", "Strzały na bramkę Gospodarz"  ,  
#                         "Strzały niecelne Gospodarz", "Rzuty rożne Gospodarz", "Interwencje bramkarzy Gospodarz",
#                         "Faule Gospodarz", "Rzuty wolne Gospodarz", "Auty bramkowe Gospodarz", 
#                         "Posiadanie piłki Gość", "Sytuacje bramkowe Gość", "Strzały na bramkę Gość",      
#                         "Strzały niecelne Gość", "Interwencje bramkarzy Gość",    
#                         "Strzały zablokowane Gospodarz", "Strzały zablokowane Gość",     
#                         "Ataki Gospodarz",  "Niebezpieczne ataki Gospodarz",
#                         "Ataki Gość",   "Niebezpieczne ataki Gość", "Podania Gospodarz",          
#                         "Podania Gość", "Podania celne Gospodarz", "Podania celne Gość"),
#   selected = "`Posiadanie piłki Gospodarz`")
# selectInput("y_variable", label = "Second variable:",
#             choices = c("Posiadanie piłki Gospodarz", "Sytuacje bramkowe Gospodarz", "Strzały na bramkę Gospodarz"  ,  
#                         "Strzały niecelne Gospodarz", "Rzuty rożne Gospodarz", "Interwencje bramkarzy Gospodarz",
#                         "Faule Gospodarz", "Rzuty wolne Gospodarz", "Auty bramkowe Gospodarz", 
#                         "Posiadanie piłki Gość", "Sytuacje bramkowe Gość", "Strzały na bramkę Gość",      
#                         "Strzały niecelne Gość", "Interwencje bramkarzy Gość",    
#                         "Strzały zablokowane Gospodarz", "Strzały zablokowane Gość",     
#                         "Ataki Gospodarz",  "Niebezpieczne ataki Gospodarz",
#                         "Ataki Gość",   "Niebezpieczne ataki Gość", "Podania Gospodarz",          
#                         "Podania Gość", "Podania celne Gospodarz", "Podania celne Gość"),
#   selected = "`Posiadanie piłki Gość`")
selectInput("club", label = "Klub",
            choices = unique(df$Gospodarz), selected = "Lech Poznań")
selectInput("season", label = "Sezon",
            choices = c(as.vector(unique(df$Sezon)), "All"), selected = "All")
```

<!-- TODO DESCRIPTION / LEGEND -->

Autorzy \
[Łukasz Chrostowski](https://github.com/LukaszChrostowski) \
[Piotr Chlebicki](https://github.com/Kertoo)

<!-- Scatter plots -->
<!-- ====================================================================== -->

<!-- Row {data-height=650} -->
<!-- ----------------------------------------------------------------------- -->
<!-- ### Scatter plots -->

<!-- ```{r} -->
<!-- renderPlotly({ -->
<!--   plot <- ggplot(data = df, aes_string(x = paste("`", input$x_variable, "`", sep = ""), y = paste("`", input$y_variable, "`", sep = ""))) + -->
<!--     geom_point() + -->
<!--     xlab(input$x_variable) + -->
<!--     ylab(input$y_variable) + -->
<!--     ggtitle(paste(input$x_variable, "vs", input$y_variable)) -->
<!--   plot -->

<!-- }) -->
<!-- ``` -->


Analiza Klubu
======================================================================

Row
-----------------------------------------------------------------------

### Z kim klub mierzył się najczęściej?

```{r}
renderPlotly({
  club <- input$club
  df_club <- df
    # Z kim najczęściej się mierzyli
  dff1 <- df_club %>% filter(Gospodarz == club) %>% group_by(Gość) %>% summarise(n = n()) %>% arrange(-n)
  dff2 <- df_club %>% filter(Gość == club) %>% group_by(Gospodarz) %>% summarise(n = n()) %>% arrange(-n)
  colnames(dff1) <- colnames(dff2) <- c("Club", "n")
  merge_df <- merge(dff1, dff2, by = "Club")
  merge_df$n <- merge_df$n.x + merge_df$n.y
  merge_df <- merge_df %>% arrange(-n) %>% head(8)
  
  g1 <- ggplot(data = merge_df, aes(x = factor(Club, levels = Club), y = n, fill = Club)) +
    geom_bar(stat = "identity") +
    xlab("Klub") +
    ylab("Liczba meczy") +
    scale_fill_manual(values = 1:nrow(merge_df)) +
    guides(fill = FALSE) +
    theme_dark()
  g1
})
```

Row
-----------------------------------------------------------------------

### Z kim klub wygrywał najczęściej?

```{r}
renderPlotly({
    club <- input$club
    df_club <- df
     # Z kim najczęściej wygrywali
    dff1 <- df_club %>% filter(Gospodarz == club) %>% group_by(Gość) %>% filter(Wynik == "H") %>% summarise(n = n()) %>% arrange(-n)
    dff2 <- df_club %>% filter(Gość == club) %>% group_by(Gospodarz) %>% filter(Wynik == "A") %>% summarise(n = n()) %>% arrange(-n)
    colnames(dff1) <- colnames(dff2) <- c("Club", "n")
    merge_df <- merge(dff1, dff2, by = "Club") 
    merge_df$n <- merge_df$n.x + merge_df$n.y
    merge_df <- merge_df %>% arrange(-n) %>% head(8)
    
    g2 <- ggplot(data = merge_df, aes(x = factor(Club, levels = Club), y = n, fill = Club)) +
      geom_bar(stat = "identity") +
      xlab("Klub") +
      ylab("Liczba meczy") +
      scale_fill_manual(values = 1:nrow(merge_df)) +
      guides(fill = FALSE) +
      theme_dark()
    g2
    
})
```

Row
-----------------------------------------------------------------------

### Z kim klub remisował najczęściej?

```{r}
renderPlotly({
    club <- input$club
    df_club <- df
    # Z kim najczęściej remisowali
    dff1 <- df_club %>% filter(Gospodarz == club) %>% group_by(Gość)  %>% filter(Wynik == "D") %>% summarise(n = n()) %>% arrange(-n)
    dff2 <- df_club %>% filter(Gość == club) %>% group_by(Gospodarz) %>% filter(Wynik == "D") %>% summarise(n = n()) %>% arrange(-n)
    colnames(dff1) <- colnames(dff2) <- c("Club", "n")
    merge_df <- merge(dff1, dff2, by = "Club") 
    merge_df$n <- merge_df$n.x + merge_df$n.y
    merge_df <- merge_df %>% arrange(-n) %>% head(8)
    
    g3 <- ggplot(data = merge_df, aes(x = factor(Club, levels = Club), y = n, fill = Club)) +
      geom_bar(stat = "identity") +
      xlab("Klub") +
      ylab("Liczba meczy") +
      scale_fill_manual(values = 1:nrow(merge_df)) +
      guides(fill = FALSE) +
      theme_dark()
    g3
})
```

Row
-----------------------------------------------------------------------
### Z kim klub przegrywał najczęściej?

```{r}
renderPlotly({
    club <- input$club
  df_club <- df
  # Z kim najczęściej przegrywali
  dff1 <- df_club %>% filter(Gospodarz == club) %>% group_by(Gość) %>% filter(Wynik == "A") %>% summarise(n = n()) %>% arrange(-n)
  dff2 <- df_club %>% filter(Gość == club) %>% group_by(Gospodarz) %>% filter(Wynik == "H") %>% summarise(n = n()) %>% arrange(-n)
  colnames(dff1) <- colnames(dff2) <- c("Club", "n")
  merge_df <- merge(dff1, dff2, by = "Club")
  merge_df$n <- merge_df$n.x + merge_df$n.y
  merge_df <- merge_df %>% arrange(-n) %>% head(8)
  
  g4 <- ggplot(data = merge_df, aes(x = factor(Club, levels = Club), y = n, fill = Club)) +
    geom_bar(stat = "identity") +
    xlab("Klub") +
    ylab("Liczba meczy") +
    scale_fill_manual(values = 1:nrow(merge_df)) +
    guides(fill = FALSE) +
    theme_dark()
  g4
})
```

Analiza sezonu
======================================================================

Row {data-height=650}
-----------------------------------------------------------------------

### Heat Mapa wyników

```{r}
renderPlot({
  season <- input$season
  if (season != "All") {
    df <- df %>% filter(Sezon == season)
    ct <-  switch(season,
              "2012/13" = ContTable_1213,
              "2013/14" = ContTable_1314,
              "2014/15" = ContTable_1415,
              "2015/16" = ContTable_1516,
              "2016/17" = ContTable_1617,
              "2017/18" = ContTable_1718,
              "2018/19" = ContTable_1819,
              "2019/20" = ContTable_1920,
              "2020/21" = ContTable_2021,
              "2021/22" = ContTable_2122)
  ct <- ConvFun(ct)
  levelplotFun(ct)
  } else {
  levelplotFun(ConvFun(ContTable_2122))
  }
})
```


Row
-----------------------------------------------------------------------

### Results distribution

```{r}
renderPlotly({
  
  season <- input$season
  if (season != "All") df <- df %>% filter(Sezon == season)
  
  ggplot(data = df, aes(x = Wynik, fill = Wynik)) +
    geom_bar() +
    ylab("Liczba Wyników") +
     xlab("Wynik") +
    scale_fill_manual(values = unique(df$Wynik)) +
    guides(fill = FALSE)

})
```

Row
-----------------------------------------------------------------------
### Rozkład Goli

```{r}
renderPlotly({
  season <- input$season
  if (season != "All") df <- df %>% filter(Sezon == season)
  
  ggplot(data = df, aes(x = `Gole Gospodarz` + `Gole Gość` )) + 
  geom_histogram(bins = 10, color = "black", fill = "white") +
  xlab("Liczba goli w meczu")
})
```

Row
-----------------------------------------------------------------------

### Liczba Goli w Sezonie

```{r}
renderPlotly({
  season <- input$season
  if (season != "All") df <- df %>% filter(Sezon == season)
  
  goals_by_season <- df %>% group_by(Sezon) %>% summarise(sum = sum(`Gole Gospodarz` + `Gole Gość`))
  
   ggplot(data = goals_by_season, aes(x = Sezon, y = sum, fill = Sezon)) +
    geom_bar(stat = "identity") +
    xlab("Sezon") +
    ylab("Liczba goli") +
    scale_fill_manual(values = 1:nrow(goals_by_season)) +
    guides(fill = FALSE)
})
```

Row
-----------------------------------------------------------------------
### Najskuteczniejsze Zespoły

```{r}
renderPlotly({
  season <- input$season
  if (season != "All") df <- df %>% filter(Sezon == season)
  
  # Number of goals by each club (sum, mean)
  A <- df %>% group_by(Gospodarz) %>% summarise(sum = sum(`Gole Gospodarz`)) %>% arrange(-sum)
  B <- df %>% group_by(Gość) %>% summarise(sum = sum(`Gole Gość`)) %>% arrange(-sum)
  colnames(A) <- colnames(B) <- c("Klub", "gole")
  mergeAB <- merge(A, B, by = "Klub")
  mergeAB$gole <- mergeAB$gole.x + mergeAB$gole.y
  goals_by_club <- mergeAB %>% arrange(-gole) %>% head(8)
  
  ggplot(data = goals_by_club, aes(x = factor(Klub, levels = Klub), y = gole, fill = Klub)) +
    geom_bar(stat = "identity") +
    xlab("Sezon") +
    ylab("Liczba goli") +
    scale_fill_manual(values = 1:nrow(goals_by_club)) +
    guides(fill = FALSE) +
    theme(axis.text.x = element_text(angle = 30, hjust = 1))
})
```

Row
-----------------------------------------------------------------------
### Ranking Zespołów według czerwonych kartek

```{r}
renderPlotly({
  season <- input$season
  if (season != "All") df <- df %>% filter(Sezon == season)
  
  A <- df %>% group_by(Gospodarz) %>% summarise(sum_red = sum(`Czerwone kartki Gospodarz`),
                                                sum_yellow = sum(`Żółte kartki Gospodarz`))
  B <- df %>% group_by(Gość) %>% summarise(sum_red = sum(`Czerwone kartki Gość`),
                                           sum_yellow = sum(`Żółte kartki Gość`)) 
  colnames(A) <- colnames(B) <-  c("Club", "red_cards", "yellow_cards")
  mergeAB <- merge(A, B, by = "Club")
  mergeAB$red_cards <- mergeAB$red_cards.x + mergeAB$red_cards.y
  mergeAB$yellow_cards <- mergeAB$yellow_cards.x + mergeAB$yellow_cards.y
  red_cards_by_club <- mergeAB %>% arrange(-red_cards) %>% head(8)
  
   ggplot(data = red_cards_by_club, aes(x = factor(Club, levels = Club), y = red_cards, fill = Club)) +
        geom_bar(stat = "identity") +
        xlab("Sezon") +
        ylab("Liczba czerwonych kartek") +
        scale_fill_manual(values = 1:nrow(red_cards_by_club)) +
        guides(fill = FALSE) +
        theme(axis.text.x = element_text(angle = 30, hjust = 1))

})
```

Row
-----------------------------------------------------------------------

### Ranking Zespołów według żółtych kartek
```{r}
renderPlotly({

  season <- input$season
  if (season != "All") df <- df %>% filter(Sezon == season)
  
  A <- df %>% group_by(Gospodarz) %>% summarise(sum_red = sum(`Czerwone kartki Gospodarz`),
                                                sum_yellow = sum(`Żółte kartki Gospodarz`))
  B <- df %>% group_by(Gość) %>% summarise(sum_red = sum(`Czerwone kartki Gość`),
                                           sum_yellow = sum(`Żółte kartki Gość`)) 
  colnames(A) <- colnames(B) <-  c("Club", "red_cards", "yellow_cards")
  mergeAB <- merge(A, B, by = "Club")
  mergeAB$red_cards <- mergeAB$red_cards.x + mergeAB$red_cards.y
  mergeAB$yellow_cards <- mergeAB$yellow_cards.x + mergeAB$yellow_cards.y
  red_cards_by_club <- mergeAB %>% arrange(-red_cards) %>% head(8)
  yellow_cards_by_club <- mergeAB %>% arrange(-yellow_cards) %>% head(8)
  
  g8 <- ggplot(data = yellow_cards_by_club, aes(x = factor(Club, levels = Club), y = yellow_cards, fill = Club)) +
    geom_bar(stat = "identity") +
    xlab("Sezon") +
    ylab("Liczba żółtych kartek") +
    scale_fill_manual(values = 1:nrow(yellow_cards_by_club)) +
    guides(fill = FALSE)
})
```

Row
-----------------------------------------------------------------------
### Liczba Meczów w miesiącu
```{r}
renderPlotly({
  season <- input$season
  if (season != "All") df <- df %>% filter(Sezon == season)
  
  # Plots by date of the match
  df_date <- df %>% group_by(month(Data)) %>% summarise(n = n()) %>% arrange(-n) %>% head()
  colnames(df_date) <- c("month", "n")
  df_date$month <- as.factor(month.name[df_date$month])
  
  ggplot(data = df_date, aes(x = factor(month, levels = month), y = n, fill = month)) +
    geom_bar(stat = "identity") +
    xlab("Miesiąc") +
    ylab("Liczba meczy") +
    scale_fill_manual(values = 1:nrow(df_date)) +
    guides(fill = FALSE)
})
```

Row
-----------------------------------------------------------------------
### Liczba meczów o danej godzinie
```{r}
renderPlotly({
  season <- input$season
  if (season != "All") df <- df %>% filter(Sezon == season)
  
    df_date <- df %>% group_by(hour(Data)) %>% summarise(n = n()) %>% arrange(-n) %>% head()
  colnames(df_date) <- c("hour", "n")
  df_date$hour <- as.factor(df_date$hour)
  
  ggplot(data = df_date, aes(x = factor(hour, levels = hour), y = n, fill = hour)) +
    geom_bar(stat = "identity") +
    xlab("Godzina meczu") +
    ylab("Liczba meczów") +
    scale_fill_manual(values = 1:nrow(df_date)) +
    guides(fill = FALSE)
})
```

Analiza Predykcyjna
======================================================================
### Model Predykcyjny {data-height=1200}

```{r}
xgb_model <- readRDS("saved_models/xgb_model.rds")
```

Row {data-height=150}
-----------------------------------------------------------------------
### Wybór drużyn
```{r}
fluidPage(
    fluidRow(
        column(6,
            selectInput("home_team", "Gospodarz:",
                       choices = unique(df$Gospodarz),
                       selected = "Lech Poznań")
        ),
        column(6,
            selectInput("away_team", "Gość:",
                       choices = unique(df$Gospodarz),
                       selected = "Legia Warszawa")
        )
    )
)
```

Row
-----------------------------------------------------------------------
### Forma drużyn i statystyki

```{r}
fluidPage(
    tags$head(
        tags$style(HTML("
            .scrollable-panel {
                height: 400px;
                overflow-y: scroll !important;
                padding-right: 15px;
                border: 1px solid #ddd;
                margin-bottom: 10px;
            }
        "))
    ),
    div(class = "scrollable-panel",
        # Forma gospodarzy
        h4("Forma gospodarzy (ostatnie 7 meczy)"),
        fluidRow(
            column(6,
                numericInput("home_goals_scored", "Średnia strzelonych goli:", 
                            value = 1.5, min = 0, max = 5, step = 0.1),
                numericInput("home_goals_conceded", "Średnia straconych goli:", 
                            value = 1.0, min = 0, max = 5, step = 0.1)
            ),
            column(6,
                numericInput("home_losses", "Liczba porażek:", 
                            value = 2, min = 0, max = 7),
                numericInput("home_draws", "Liczba remisów:", 
                            value = 2, min = 0, max = 7)
            )
        ),
        
        # Forma gości
        h4("Forma gości (ostatnie 7 meczy)"),
        fluidRow(
            column(6,
                numericInput("away_goals_scored", "Średnia strzelonych goli:", 
                            value = 1.5, min = 0, max = 5, step = 0.1),
                numericInput("away_goals_conceded", "Średnia straconych goli:", 
                            value = 1.0, min = 0, max = 5, step = 0.1)
            ),
            column(6,
                numericInput("away_losses", "Liczba porażek:", 
                            value = 2, min = 0, max = 7),
                numericInput("away_draws", "Liczba remisów:", 
                            value = 2, min = 0, max = 7)
            )
        ),
        
        # Statystyki meczowe
        h4("Przewidywane statystyki meczu"),
        fluidRow(
            column(6,
                numericInput("home_possession", "Posiadanie piłki gospodarzy (%):", 
                            value = 50, min = 0, max = 100),
                numericInput("home_shots_on_target", "Strzały celne gospodarzy:", 
                            value = 5, min = 0, max = 20),
                numericInput("home_corners", "Rzuty rożne gospodarzy:", 
                            value = 5, min = 0, max = 15)
            ),
            column(6,
                numericInput("away_shots_on_target", "Strzały celne gości:", 
                            value = 5, min = 0, max = 20),
                numericInput("away_corners", "Rzuty rożne gości:", 
                            value = 5, min = 0, max = 15)
            )
        )
    )
)
```

Row
-----------------------------------------------------------------------
### Predykcja wyniku

```{r}
fluidPage(
    tags$style(HTML("
        .prediction-result { 
            font-size: 24px; 
            text-align: center; 
            margin: 20px;
            padding: 20px;
            background-color: #f8f9fa;
            border-radius: 5px;
        }
    ")),
    
    fluidRow(
        column(12,
            div(style="text-align: center; margin: 20px;",
                actionButton("predict", "Przewiduj wynik", 
                           class = "btn-primary btn-lg")
            ),
            wellPanel(
                h4(textOutput("teams_text"), align = "center"),
                div(
                    class = "prediction-result",
                    textOutput("pred_text")
                )
            )
        )
    )
)
```


```{r}
output$teams_text <- renderText({
    req(input$home_team, input$away_team)  
    paste(input$home_team, "vs", input$away_team)
})

# Utworzenie reaktywnej wartości dla predykcji
predictionValue <- eventReactive(
    input$predict,
    {
        req(input$home_team != "", input$away_team != "")  
        
        # Przygotowanie danych
        input_data <- {
            pred_vector <- numeric(87)
            names(pred_vector) <- c(
            # Drużyny gospodarzy
            "GospodarzArka Gdynia", "GospodarzBrukBet T.", "GospodarzCracovia", "GospodarzGKS Bełchatów",
            "GospodarzGórnik Łęczna", "GospodarzGórnik Zabrze", "GospodarzJagiellonia Białystok", "GospodarzKorona Kielce",
            "GospodarzLech Poznań", "GospodarzLechia Gdańsk", "GospodarzLegia Warszawa", "GospodarzŁKS Łódź",
            "GospodarzMiedź Legnica", "GospodarzPiast Gliwice", "GospodarzPodbeskidzie BB", "GospodarzPogoń Szczecin",
            "GospodarzRadomiak Radom", "GospodarzRaków Częstochowa", "GospodarzRuch Chorzów", "GospodarzSandecja Nowy Sącz",
            "GospodarzŚląsk Wrocław", "GospodarzStal Mielec", "GospodarzWarta Poznań", "GospodarzWidzew Łódź",
            "GospodarzWisła Kraków", "GospodarzWisła Płock", "GospodarzZagłębie Lubin", "GospodarzZagłębie Sosnowiec",
            "GospodarzZawisza Bydgoszcz",
            
            # Drużyny gości
            "GośćBrukBet T.", "GośćCracovia", "GośćGKS Bełchatów", "GośćGórnik Łęczna",
            "GośćGórnik Zabrze", "GośćJagiellonia Białystok", "GośćKorona Kielce", "GośćLech Poznań",
            "GośćLechia Gdańsk", "GośćLegia Warszawa", "GośćŁKS Łódź", "GośćMiedź Legnica",
            "GośćPiast Gliwice", "GośćPodbeskidzie BB", "GośćPogoń Szczecin", "GośćRadomiak Radom",
            "GośćRaków Częstochowa", "GośćRuch Chorzów", "GośćSandecja Nowy Sącz", "GośćŚląsk Wrocław",
            "GośćStal Mielec", "GośćWarta Poznań", "GośćWidzew Łódź", "GośćWisła Kraków",
            "GośćWisła Płock", "GośćZagłębie Lubin", "GośćZagłębie Sosnowiec", "GośćZawisza Bydgoszcz",
            
            # Statystyki meczowe
            "`Posiadanie piłki Gospodarz`", "`Sytuacje bramkowe Gospodarz`", "`Strzały na bramkę Gospodarz`",
            "`Strzały niecelne Gospodarz`", "`Rzuty rożne Gospodarz`", "`Spalone Gospodarz`",
            "`Interwencje bramkarzy Gospodarz`", "`Faule Gospodarz`", "`Żółte kartki Gospodarz`",
            "`Czerwone kartki Gospodarz`", "`Posiadanie piłki Gość`", "`Sytuacje bramkowe Gość`",
            "`Strzały na bramkę Gość`", "`Strzały niecelne Gość`", "`Rzuty rożne Gość`",
            "`Spalone Gość`", "`Interwencje bramkarzy Gość`", "`Faule Gość`", "`Żółte kartki Gość`",
            "`Czerwone kartki Gość`", "`Gole Gospodarz`", "`Gole Gość`",
            
            # Dodatkowe zmienne
            "LowerLeague_Home1", "LowerLeague_Away1", "`Porażka Gospodarz`", "`Remis Gospodarz`",
            "`Porażka Gość`", "`Remis Gość`", "`Gole stracone Gość`", "`Gole stracone Gospodarz`"
          )
            
            # Ustawienie flag dla drużyn (one-hot encoding)
            home_team_col <- paste0("Gospodarz", input$home_team)
            away_team_col <- paste0("Gość", input$away_team)
            pred_vector[home_team_col] <- 1
            pred_vector[away_team_col] <- 1
            
            # Ustawienie pozostałych zmiennych
            pred_vector["`Posiadanie piłki Gospodarz`"] <- input$home_possession
            pred_vector["`Strzały na bramkę Gospodarz`"] <- input$home_shots_on_target
            pred_vector["`Strzały na bramkę Gość`"] <- input$away_shots_on_target
            pred_vector["`Rzuty rożne Gospodarz`"] <- input$home_corners
            pred_vector["`Rzuty rożne Gość`"] <- input$away_corners
            pred_vector["`Porażka Gospodarz`"] <- input$home_losses
            pred_vector["`Remis Gospodarz`"] <- input$home_draws
            pred_vector["`Porażka Gość`"] <- input$away_losses
            pred_vector["`Remis Gość`"] <- input$away_draws
            pred_vector["`Gole stracone Gość`"] <- input$away_goals_conceded
            pred_vector["`Gole stracone Gospodarz`"] <- input$home_goals_conceded
            
            matrix(pred_vector, nrow = 1)
        }
        
        pred_matrix <- xgb.DMatrix(input_data)
        pred_prob <- predict(xgb_model, pred_matrix, reshape = TRUE)
        
        paste(
            sprintf("\nWygrana %s: %.1f%%", input$home_team, pred_prob[3] * 100),
            sprintf("\nRemis: %.1f%%", pred_prob[2] * 100),
            sprintf("\nWygrana %s: %.1f%%", input$away_team, pred_prob[1] * 100),
            sep = "\n"
        )
    },
    ignoreNULL = FALSE
)

output$pred_text <- renderText({
    predictionValue()
})
```


